# size constants
WIDTH = 1080
HEIGHT = 800

LEVEL_WIDTH, LEVEL_HEIGHT = 27, 20

TILE_WIDTH = WIDTH / LEVEL_WIDTH
TILE_HEIGHT = HEIGHT / LEVEL_HEIGHT

# constants for moving
DELTA_ANGLE = 2
DELTA_DISTANCE_FOR_TANK = 3

# frames stuff
FPS = 60
BOOM_FPS = 60
NUM_OF_FRAMES = 360 // DELTA_ANGLE

# level generation
LEVEL_NAME = "generated.txt"
